# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               My blog
tagline:             '總是要留下走過得痕跡'
description:         '希望可以留下一些 自己學習的痕跡 在迷失時 可以找尋最初的目標 <a href="https://github.com/LunaHuang" target="_blank">Luna</a> .'
url:                 https://lunahuang.github.io
baseurl:			 https://lunahuang.github.io
paginate:            5

# About/contact
author:
  name:              Luna Huang
  url:               ''
  email:             shiulinghuang@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
